"""Auto-generated by Repo2RLEnv code_instruct cli_app mode (kwok backend).

Session-scoped kwokctl cluster + delete-non-system-namespaces reset between
tests. The agent's submission runs as a subprocess; we boot a fresh kwok
cluster on a random loopback port and write KUBECONFIG so both the test
kubernetes.client and the submission subprocess reach the same apiserver.
"""

import ipaddress
import os
import shutil
import socket as _socket
import subprocess
import sys
import time as _time
import http.client as _http

_R2E_ORIG_CONNECT = _socket.socket.connect
_R2E_BLOCKED_SUFFIXES = ('pypi.org', 'pythonhosted.org', 'github.com', 'githubusercontent.com', 'awscli.amazonaws.com', 's3.amazonaws.com', 'min.io', 'debian.org', 'ubuntu.com', 'pypi.tuna.tsinghua.edu.cn', 'pypi.mirrors.ustc.edu.cn', 'mirrors.aliyun.com', 'mirrors.cloud.tencent.com', 'pypi.douban.com', 'mirrors.huaweicloud.com', 'anaconda.com', 'anaconda.org', 'eks.amazonaws.com', 'googleapis.com', 'azmk8s.io',)

import stat as _r2e_stat


def _r2e_ensure_executable(path):
    try:
        st = os.stat(path)
        os.chmod(path, st.st_mode | _r2e_stat.S_IXUSR | _r2e_stat.S_IXGRP | _r2e_stat.S_IXOTH)
    except OSError:
        pass


if os.path.exists("/workspace/submission/kubectl"):
    _r2e_ensure_executable("/workspace/submission/kubectl")
    _R2E_CLI_PREFIX = ["/workspace/submission/kubectl"]
else:
    _R2E_CLI_PREFIX = [sys.executable, "/workspace/submission/main.py"]


def _r2e_guarded_connect(self, address):
    if self.family in (_socket.AF_INET, _socket.AF_INET6) and isinstance(address, tuple):
        host = address[0]
        try:
            ip = ipaddress.ip_address(host)
        except ValueError:
            for suffix in _R2E_BLOCKED_SUFFIXES:
                if host.lower() == suffix or host.lower().endswith("." + suffix):
                    raise RuntimeError(f"r2e:network-isolation: connect to {host!r} blocked")
        else:
            if not (ip.is_loopback or ip.is_private or ip.is_link_local):
                raise RuntimeError(
                    f"r2e:network-isolation: connect to public IP {host!r} blocked"
                )
    return _R2E_ORIG_CONNECT(self, address)


_socket.socket.connect = _r2e_guarded_connect
def _r2e_guarded_connect_ex(self, addr):
    import errno as _errno
    try:
        _r2e_guarded_connect(self, addr)
        return 0
    except RuntimeError:
        return _errno.EACCES
    except OSError as exc:
        return exc.errno
_socket.socket.connect_ex = _r2e_guarded_connect_ex

import pytest


def pytest_configure(config):
    _kubectl = "/workspace/submission/kubectl"
    _mainpy = "/workspace/submission/main.py"
    _kubectl_exists = os.path.exists(_kubectl)
    _mainpy_exists = os.path.exists(_mainpy)
    if not (_kubectl_exists or _mainpy_exists):
        pytest.exit(
            f"Anti-NOP guard FAILED: no submission entrypoint found "
            f"(tried {_kubectl}, {_mainpy}). Reward=0.",
            returncode=1,
        )
    if _kubectl_exists:
        if not os.access(_kubectl, os.X_OK):
            pytest.exit(
                "submission/kubectl missing/non-exec/empty (not executable). Reward=0.",
                returncode=1,
            )
        if os.path.getsize(_kubectl) <= 0:
            pytest.exit(
                "submission/kubectl missing/non-exec/empty (zero-byte file). Reward=0.",
                returncode=1,
            )
    if shutil.which("kubectl") is None:
        pytest.exit(
            "Anti-NOP guard FAILED: kubectl binary not found on PATH. Reward=0.",
            returncode=1,
        )
    if shutil.which("kwokctl") is None:
        pytest.exit(
            "Anti-NOP guard FAILED: kwokctl binary not found on PATH. Reward=0.",
            returncode=1,
        )


def _grab_free_port(retries=3):
    """Retry on bind-time races; rare but observed on busy CI."""
    last_err = None
    for _ in range(retries):
        try:
            sock = _socket.socket()
            sock.bind(("127.0.0.1", 0))
            port = sock.getsockname()[1]
            sock.close()
            return port
        except OSError as e:
            last_err = e
            _time.sleep(0.05)
    raise RuntimeError(f"could not bind ephemeral port: {last_err}")


@pytest.fixture(scope="session")
def kwok_cluster(tmp_path_factory):
    port = _grab_free_port()
    kubeconfig = tmp_path_factory.mktemp("kwok") / "kubeconfig"
    cluster_name = f"r2e-{os.getpid()}"

    subprocess.run(
        [
            "kwokctl",
            "create",
            "cluster",
            "--runtime=binary",
            f"--name={cluster_name}",
            f"--kube-apiserver-port={port}",
            "--wait=600s",
            "--etcd-binary=/usr/local/bin/etcd",
            "--kube-apiserver-binary=/usr/local/bin/kube-apiserver",
            "--kube-controller-manager-binary=/usr/local/bin/kube-controller-manager",
            "--kube-scheduler-binary=/usr/local/bin/kube-scheduler",
            "--kwok-controller-binary=/usr/local/bin/kwok",
        ],
        check=True,
        capture_output=True,
        text=True,
        timeout=900,
    )

    kubeconfig_bytes = subprocess.run(
        ["kwokctl", "get", "kubeconfig", f"--name={cluster_name}"],
        check=True,
        capture_output=True,
        text=True,
        timeout=10,
    ).stdout
    kubeconfig.write_text(kubeconfig_bytes)
    os.environ["KUBECONFIG"] = str(kubeconfig)

    import re as _re
    _server_match = _re.search(r"server:\s*https?://([^:\s]+):(\d+)", kubeconfig_bytes)
    if _server_match:
        actual_host = _server_match.group(1)
        actual_port = int(_server_match.group(2))
    else:
        actual_host = "127.0.0.1"
        actual_port = port
    endpoint = f"{actual_host}:{actual_port}"
    for _ in range(3000):
        try:
            with _socket.create_connection((actual_host, actual_port), timeout=0.2):
                break
        except OSError:
            pass
        _time.sleep(0.1)
    else:
        subprocess.run(
            ["kwokctl", "delete", "cluster", f"--name={cluster_name}"],
            check=False,
            capture_output=True,
        )
        raise RuntimeError(f"kwok apiserver at {endpoint} not ready within 300s")

    try:
        yield {"endpoint": endpoint, "kubeconfig": str(kubeconfig), "name": cluster_name}
    finally:
        subprocess.run(
            ["kwokctl", "delete", "cluster", f"--name={cluster_name}"],
            check=False,
            capture_output=True,
            timeout=30,
        )


@pytest.fixture
def k8s_client(kwok_cluster):
    from kubernetes import client, config as _kconfig

    _kconfig.load_kube_config(config_file=kwok_cluster["kubeconfig"])
    return client.CoreV1Api(client.ApiClient())


@pytest.fixture(autouse=True)
def _reset_kwok(kwok_cluster):
    """Wipe non-system namespaces + purge default's contents between tests.

    Preserves kube-system, kube-public, kube-node-lease, default (matches
    kubectl's own "protected" namespaces list). All other namespaces (and
    their contents) are hard-deleted. The `default` namespace itself is
    kept but its user-visible contents are purged so ResourceQuotas /
    Pods / etc. from earlier tests cannot poison later tests.
    """
    _system = {"kube-system", "kube-public", "kube-node-lease", "default"}
    for _ in range(5):
        result = subprocess.run(
            ["kubectl", "--kubeconfig", kwok_cluster["kubeconfig"],
             "get", "ns", "-o", "name"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        stale = [
            line.removeprefix("namespace/").strip()
            for line in result.stdout.splitlines()
            if line.strip() and line.removeprefix("namespace/").strip() not in _system
        ]
        if not stale:
            break
        subprocess.run(
            ["kubectl", "--kubeconfig", kwok_cluster["kubeconfig"],
             "delete", "ns", *stale, "--wait=true", "--grace-period=0", "--force"],
            capture_output=True,
            timeout=30,
        )
    subprocess.run(
        ["kubectl", "--kubeconfig", kwok_cluster["kubeconfig"],
         "delete",
         "pods,services,resourcequotas,limitranges,deployments,replicasets,"
         "statefulsets,daemonsets,jobs,cronjobs,configmaps,secrets,"
         "persistentvolumeclaims,ingresses,serviceaccounts",
         "--all", "-n", "default", "--grace-period=0", "--force"],
        capture_output=True,
        timeout=30,
    )
    yield


@pytest.fixture
def cli(kwok_cluster):
    def _run(*args, env_overrides=None, timeout=60, input=None):
        env = os.environ.copy()
        env["KUBECONFIG"] = kwok_cluster["kubeconfig"]
        if env_overrides:
            env.update(env_overrides)
        return subprocess.run(
            [*_R2E_CLI_PREFIX, *args],
            env=env,
            input=input,
            capture_output=True,
            text=True,
            timeout=timeout,
        )

    return _run


@pytest.fixture
def kubectl_bin(kwok_cluster):
    """Direct kubectl invoker (bypasses the submission).

    Used by tests that need to set up cluster state as a precondition
    without going through the agent's submission (e.g. seeding a
    Deployment before running `submission cli get deployment ...`).
    """
    def _run(args, *, input=None, timeout=30.0):
        env = os.environ.copy()
        env["KUBECONFIG"] = kwok_cluster["kubeconfig"]
        _kubectl = "/usr/local/bin/kubectl"
        return subprocess.run(
            [_kubectl, "--kubeconfig", kwok_cluster["kubeconfig"], *args],
            env=env,
            input=input,
            capture_output=True,
            text=True,
            timeout=timeout,
        )

    return _run
